name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Clone repository  
        uses: actions/checkout@v2  
      - name: Use Node.js 20  
        uses: actions/setup-node@v2  
        with:  
          node-version: '20.x'  
      - run: npm install  
      - run: node main.js

      - name: download
        run: |
          git config --local user.email "justjavac@gmail.com"
          git config --local user.name "迷渡"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          ./bin/youtube-dl --config-location config.txt
          git add .
          git commit -m "download youtube video"
          git push
